/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type CompressedBinDepositAmount2 = { binId: number; amount: number };

export type CompressedBinDepositAmount2Args = CompressedBinDepositAmount2;

export function getCompressedBinDepositAmount2Encoder(): FixedSizeEncoder<CompressedBinDepositAmount2Args> {
  return getStructEncoder([
    ['binId', getI32Encoder()],
    ['amount', getU32Encoder()],
  ]);
}

export function getCompressedBinDepositAmount2Decoder(): FixedSizeDecoder<CompressedBinDepositAmount2> {
  return getStructDecoder([
    ['binId', getI32Decoder()],
    ['amount', getU32Decoder()],
  ]);
}

export function getCompressedBinDepositAmount2Codec(): FixedSizeCodec<
  CompressedBinDepositAmount2Args,
  CompressedBinDepositAmount2
> {
  return combineCodec(
    getCompressedBinDepositAmount2Encoder(),
    getCompressedBinDepositAmount2Decoder()
  );
}
