/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getBinLiquidityDistributionDecoder,
  getBinLiquidityDistributionEncoder,
  type BinLiquidityDistribution,
  type BinLiquidityDistributionArgs,
} from '.';

export type LiquidityParameter = {
  /** Amount of X token to deposit */
  amountX: bigint;
  /** Amount of Y token to deposit */
  amountY: bigint;
  /** Liquidity distribution to each bins */
  binLiquidityDist: Array<BinLiquidityDistribution>;
};

export type LiquidityParameterArgs = {
  /** Amount of X token to deposit */
  amountX: number | bigint;
  /** Amount of Y token to deposit */
  amountY: number | bigint;
  /** Liquidity distribution to each bins */
  binLiquidityDist: Array<BinLiquidityDistributionArgs>;
};

export function getLiquidityParameterEncoder(): Encoder<LiquidityParameterArgs> {
  return getStructEncoder([
    ['amountX', getU64Encoder()],
    ['amountY', getU64Encoder()],
    ['binLiquidityDist', getArrayEncoder(getBinLiquidityDistributionEncoder())],
  ]);
}

export function getLiquidityParameterDecoder(): Decoder<LiquidityParameter> {
  return getStructDecoder([
    ['amountX', getU64Decoder()],
    ['amountY', getU64Decoder()],
    ['binLiquidityDist', getArrayDecoder(getBinLiquidityDistributionDecoder())],
  ]);
}

export function getLiquidityParameterCodec(): Codec<
  LiquidityParameterArgs,
  LiquidityParameter
> {
  return combineCodec(
    getLiquidityParameterEncoder(),
    getLiquidityParameterDecoder()
  );
}
