/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum TokenProgramFlags {
  TokenProgram,
  TokenProgram2022,
}

export type TokenProgramFlagsArgs = TokenProgramFlags;

export function getTokenProgramFlagsEncoder(): FixedSizeEncoder<TokenProgramFlagsArgs> {
  return getEnumEncoder(TokenProgramFlags);
}

export function getTokenProgramFlagsDecoder(): FixedSizeDecoder<TokenProgramFlags> {
  return getEnumDecoder(TokenProgramFlags);
}

export function getTokenProgramFlagsCodec(): FixedSizeCodec<
  TokenProgramFlagsArgs,
  TokenProgramFlags
> {
  return combineCodec(
    getTokenProgramFlagsEncoder(),
    getTokenProgramFlagsDecoder()
  );
}
