/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_PRESET_PARAMETER2_DISCRIMINATOR = new Uint8Array([
  39, 25, 95, 107, 116, 17, 115, 28,
]);

export function getClosePresetParameter2DiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_PRESET_PARAMETER2_DISCRIMINATOR
  );
}

export type ClosePresetParameter2Instruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountPresetParameter extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountRentReceiver extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPresetParameter extends string
        ? WritableAccount<TAccountPresetParameter>
        : TAccountPresetParameter,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountRentReceiver extends string
        ? WritableAccount<TAccountRentReceiver>
        : TAccountRentReceiver,
      ...TRemainingAccounts,
    ]
  >;

export type ClosePresetParameter2InstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClosePresetParameter2InstructionDataArgs = {};

export function getClosePresetParameter2InstructionDataEncoder(): FixedSizeEncoder<ClosePresetParameter2InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_PRESET_PARAMETER2_DISCRIMINATOR,
    })
  );
}

export function getClosePresetParameter2InstructionDataDecoder(): FixedSizeDecoder<ClosePresetParameter2InstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClosePresetParameter2InstructionDataCodec(): FixedSizeCodec<
  ClosePresetParameter2InstructionDataArgs,
  ClosePresetParameter2InstructionData
> {
  return combineCodec(
    getClosePresetParameter2InstructionDataEncoder(),
    getClosePresetParameter2InstructionDataDecoder()
  );
}

export type ClosePresetParameter2Input<
  TAccountPresetParameter extends string = string,
  TAccountAdmin extends string = string,
  TAccountRentReceiver extends string = string,
> = {
  presetParameter: Address<TAccountPresetParameter>;
  admin: TransactionSigner<TAccountAdmin>;
  rentReceiver: Address<TAccountRentReceiver>;
};

export function getClosePresetParameter2Instruction<
  TAccountPresetParameter extends string,
  TAccountAdmin extends string,
  TAccountRentReceiver extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: ClosePresetParameter2Input<
    TAccountPresetParameter,
    TAccountAdmin,
    TAccountRentReceiver
  >,
  config?: { programAddress?: TProgramAddress }
): ClosePresetParameter2Instruction<
  TProgramAddress,
  TAccountPresetParameter,
  TAccountAdmin,
  TAccountRentReceiver
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    presetParameter: { value: input.presetParameter ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
    rentReceiver: { value: input.rentReceiver ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.presetParameter),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.rentReceiver),
    ],
    data: getClosePresetParameter2InstructionDataEncoder().encode({}),
    programAddress,
  } as ClosePresetParameter2Instruction<
    TProgramAddress,
    TAccountPresetParameter,
    TAccountAdmin,
    TAccountRentReceiver
  >);
}

export type ParsedClosePresetParameter2Instruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    presetParameter: TAccountMetas[0];
    admin: TAccountMetas[1];
    rentReceiver: TAccountMetas[2];
  };
  data: ClosePresetParameter2InstructionData;
};

export function parseClosePresetParameter2Instruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClosePresetParameter2Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      presetParameter: getNextAccount(),
      admin: getNextAccount(),
      rentReceiver: getNextAccount(),
    },
    data: getClosePresetParameter2InstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
