/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CREATE_CLAIM_PROTOCOL_FEE_OPERATOR_DISCRIMINATOR = new Uint8Array([
  51, 19, 150, 252, 105, 157, 48, 91,
]);

export function getCreateClaimProtocolFeeOperatorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_CLAIM_PROTOCOL_FEE_OPERATOR_DISCRIMINATOR
  );
}

export type CreateClaimProtocolFeeOperatorInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountClaimFeeOperator extends string | AccountMeta<string> = string,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountClaimFeeOperator extends string
        ? WritableAccount<TAccountClaimFeeOperator>
        : TAccountClaimFeeOperator,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateClaimProtocolFeeOperatorInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CreateClaimProtocolFeeOperatorInstructionDataArgs = {};

export function getCreateClaimProtocolFeeOperatorInstructionDataEncoder(): FixedSizeEncoder<CreateClaimProtocolFeeOperatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CREATE_CLAIM_PROTOCOL_FEE_OPERATOR_DISCRIMINATOR,
    })
  );
}

export function getCreateClaimProtocolFeeOperatorInstructionDataDecoder(): FixedSizeDecoder<CreateClaimProtocolFeeOperatorInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCreateClaimProtocolFeeOperatorInstructionDataCodec(): FixedSizeCodec<
  CreateClaimProtocolFeeOperatorInstructionDataArgs,
  CreateClaimProtocolFeeOperatorInstructionData
> {
  return combineCodec(
    getCreateClaimProtocolFeeOperatorInstructionDataEncoder(),
    getCreateClaimProtocolFeeOperatorInstructionDataDecoder()
  );
}

export type CreateClaimProtocolFeeOperatorInput<
  TAccountClaimFeeOperator extends string = string,
  TAccountOperator extends string = string,
  TAccountAdmin extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  claimFeeOperator: Address<TAccountClaimFeeOperator>;
  operator: Address<TAccountOperator>;
  admin: TransactionSigner<TAccountAdmin>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCreateClaimProtocolFeeOperatorInstruction<
  TAccountClaimFeeOperator extends string,
  TAccountOperator extends string,
  TAccountAdmin extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: CreateClaimProtocolFeeOperatorInput<
    TAccountClaimFeeOperator,
    TAccountOperator,
    TAccountAdmin,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateClaimProtocolFeeOperatorInstruction<
  TProgramAddress,
  TAccountClaimFeeOperator,
  TAccountOperator,
  TAccountAdmin,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    claimFeeOperator: {
      value: input.claimFeeOperator ?? null,
      isWritable: true,
    },
    operator: { value: input.operator ?? null, isWritable: false },
    admin: { value: input.admin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.claimFeeOperator),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateClaimProtocolFeeOperatorInstructionDataEncoder().encode({}),
    programAddress,
  } as CreateClaimProtocolFeeOperatorInstruction<
    TProgramAddress,
    TAccountClaimFeeOperator,
    TAccountOperator,
    TAccountAdmin,
    TAccountSystemProgram
  >);
}

export type ParsedCreateClaimProtocolFeeOperatorInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    claimFeeOperator: TAccountMetas[0];
    operator: TAccountMetas[1];
    admin: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CreateClaimProtocolFeeOperatorInstructionData;
};

export function parseCreateClaimProtocolFeeOperatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateClaimProtocolFeeOperatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      claimFeeOperator: getNextAccount(),
      operator: getNextAccount(),
      admin: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateClaimProtocolFeeOperatorInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
