/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_ACTIVATION_POINT_DISCRIMINATOR = new Uint8Array([
  91, 249, 15, 165, 26, 129, 254, 125,
]);

export function getSetActivationPointDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_ACTIVATION_POINT_DISCRIMINATOR
  );
}

export type SetActivationPointInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountLbPair extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountLbPair extends string
        ? WritableAccount<TAccountLbPair>
        : TAccountLbPair,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetActivationPointInstructionData = {
  discriminator: ReadonlyUint8Array;
  activationPoint: bigint;
};

export type SetActivationPointInstructionDataArgs = {
  activationPoint: number | bigint;
};

export function getSetActivationPointInstructionDataEncoder(): FixedSizeEncoder<SetActivationPointInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['activationPoint', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_ACTIVATION_POINT_DISCRIMINATOR })
  );
}

export function getSetActivationPointInstructionDataDecoder(): FixedSizeDecoder<SetActivationPointInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['activationPoint', getU64Decoder()],
  ]);
}

export function getSetActivationPointInstructionDataCodec(): FixedSizeCodec<
  SetActivationPointInstructionDataArgs,
  SetActivationPointInstructionData
> {
  return combineCodec(
    getSetActivationPointInstructionDataEncoder(),
    getSetActivationPointInstructionDataDecoder()
  );
}

export type SetActivationPointInput<
  TAccountLbPair extends string = string,
  TAccountAdmin extends string = string,
> = {
  lbPair: Address<TAccountLbPair>;
  admin: TransactionSigner<TAccountAdmin>;
  activationPoint: SetActivationPointInstructionDataArgs['activationPoint'];
};

export function getSetActivationPointInstruction<
  TAccountLbPair extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: SetActivationPointInput<TAccountLbPair, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress }
): SetActivationPointInstruction<
  TProgramAddress,
  TAccountLbPair,
  TAccountAdmin
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    lbPair: { value: input.lbPair ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.lbPair), getAccountMeta(accounts.admin)],
    data: getSetActivationPointInstructionDataEncoder().encode(
      args as SetActivationPointInstructionDataArgs
    ),
    programAddress,
  } as SetActivationPointInstruction<
    TProgramAddress,
    TAccountLbPair,
    TAccountAdmin
  >);
}

export type ParsedSetActivationPointInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    lbPair: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: SetActivationPointInstructionData;
};

export function parseSetActivationPointInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetActivationPointInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { lbPair: getNextAccount(), admin: getNextAccount() },
    data: getSetActivationPointInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
