/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_PAIR_STATUS_DISCRIMINATOR = new Uint8Array([
  67, 248, 231, 137, 154, 149, 217, 174,
]);

export function getSetPairStatusDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_PAIR_STATUS_DISCRIMINATOR
  );
}

export type SetPairStatusInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountLbPair extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountLbPair extends string
        ? WritableAccount<TAccountLbPair>
        : TAccountLbPair,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetPairStatusInstructionData = {
  discriminator: ReadonlyUint8Array;
  status: number;
};

export type SetPairStatusInstructionDataArgs = { status: number };

export function getSetPairStatusInstructionDataEncoder(): FixedSizeEncoder<SetPairStatusInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['status', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_PAIR_STATUS_DISCRIMINATOR })
  );
}

export function getSetPairStatusInstructionDataDecoder(): FixedSizeDecoder<SetPairStatusInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['status', getU8Decoder()],
  ]);
}

export function getSetPairStatusInstructionDataCodec(): FixedSizeCodec<
  SetPairStatusInstructionDataArgs,
  SetPairStatusInstructionData
> {
  return combineCodec(
    getSetPairStatusInstructionDataEncoder(),
    getSetPairStatusInstructionDataDecoder()
  );
}

export type SetPairStatusInput<
  TAccountLbPair extends string = string,
  TAccountAdmin extends string = string,
> = {
  lbPair: Address<TAccountLbPair>;
  admin: TransactionSigner<TAccountAdmin>;
  status: SetPairStatusInstructionDataArgs['status'];
};

export function getSetPairStatusInstruction<
  TAccountLbPair extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: SetPairStatusInput<TAccountLbPair, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress }
): SetPairStatusInstruction<TProgramAddress, TAccountLbPair, TAccountAdmin> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    lbPair: { value: input.lbPair ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [getAccountMeta(accounts.lbPair), getAccountMeta(accounts.admin)],
    data: getSetPairStatusInstructionDataEncoder().encode(
      args as SetPairStatusInstructionDataArgs
    ),
    programAddress,
  } as SetPairStatusInstruction<
    TProgramAddress,
    TAccountLbPair,
    TAccountAdmin
  >);
}

export type ParsedSetPairStatusInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    lbPair: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: SetPairStatusInstructionData;
};

export function parseSetPairStatusInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetPairStatusInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { lbPair: getNextAccount(), admin: getNextAccount() },
    data: getSetPairStatusInstructionDataDecoder().decode(instruction.data),
  };
}
