/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_PAIR_STATUS_PERMISSIONLESS_DISCRIMINATOR = new Uint8Array([
  78, 59, 152, 211, 70, 183, 46, 208,
]);

export function getSetPairStatusPermissionlessDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_PAIR_STATUS_PERMISSIONLESS_DISCRIMINATOR
  );
}

export type SetPairStatusPermissionlessInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountLbPair extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountLbPair extends string
        ? WritableAccount<TAccountLbPair>
        : TAccountLbPair,
      TAccountCreator extends string
        ? ReadonlySignerAccount<TAccountCreator> &
            AccountSignerMeta<TAccountCreator>
        : TAccountCreator,
      ...TRemainingAccounts,
    ]
  >;

export type SetPairStatusPermissionlessInstructionData = {
  discriminator: ReadonlyUint8Array;
  status: number;
};

export type SetPairStatusPermissionlessInstructionDataArgs = { status: number };

export function getSetPairStatusPermissionlessInstructionDataEncoder(): FixedSizeEncoder<SetPairStatusPermissionlessInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['status', getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_PAIR_STATUS_PERMISSIONLESS_DISCRIMINATOR,
    })
  );
}

export function getSetPairStatusPermissionlessInstructionDataDecoder(): FixedSizeDecoder<SetPairStatusPermissionlessInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['status', getU8Decoder()],
  ]);
}

export function getSetPairStatusPermissionlessInstructionDataCodec(): FixedSizeCodec<
  SetPairStatusPermissionlessInstructionDataArgs,
  SetPairStatusPermissionlessInstructionData
> {
  return combineCodec(
    getSetPairStatusPermissionlessInstructionDataEncoder(),
    getSetPairStatusPermissionlessInstructionDataDecoder()
  );
}

export type SetPairStatusPermissionlessInput<
  TAccountLbPair extends string = string,
  TAccountCreator extends string = string,
> = {
  lbPair: Address<TAccountLbPair>;
  creator: TransactionSigner<TAccountCreator>;
  status: SetPairStatusPermissionlessInstructionDataArgs['status'];
};

export function getSetPairStatusPermissionlessInstruction<
  TAccountLbPair extends string,
  TAccountCreator extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: SetPairStatusPermissionlessInput<TAccountLbPair, TAccountCreator>,
  config?: { programAddress?: TProgramAddress }
): SetPairStatusPermissionlessInstruction<
  TProgramAddress,
  TAccountLbPair,
  TAccountCreator
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    lbPair: { value: input.lbPair ?? null, isWritable: true },
    creator: { value: input.creator ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.lbPair),
      getAccountMeta(accounts.creator),
    ],
    data: getSetPairStatusPermissionlessInstructionDataEncoder().encode(
      args as SetPairStatusPermissionlessInstructionDataArgs
    ),
    programAddress,
  } as SetPairStatusPermissionlessInstruction<
    TProgramAddress,
    TAccountLbPair,
    TAccountCreator
  >);
}

export type ParsedSetPairStatusPermissionlessInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    lbPair: TAccountMetas[0];
    creator: TAccountMetas[1];
  };
  data: SetPairStatusPermissionlessInstructionData;
};

export function parseSetPairStatusPermissionlessInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetPairStatusPermissionlessInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { lbPair: getNextAccount(), creator: getNextAccount() },
    data: getSetPairStatusPermissionlessInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
