/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_DYNAMIC_FEE_PARAMETERS_DISCRIMINATOR = new Uint8Array([
  92, 161, 46, 246, 255, 189, 22, 22,
]);

export function getUpdateDynamicFeeParametersDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_DYNAMIC_FEE_PARAMETERS_DISCRIMINATOR
  );
}

export type UpdateDynamicFeeParametersInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountLbPair extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountLbPair extends string
        ? WritableAccount<TAccountLbPair>
        : TAccountLbPair,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateDynamicFeeParametersInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Filter period determine high frequency trading time window. */
  filterPeriod: number;
  /** Decay period determine when the volatile fee start decay / decrease. */
  decayPeriod: number;
  /** Reduction factor controls the volatile fee rate decrement rate. */
  reductionFactor: number;
  /** Used to scale the variable fee component depending on the dynamic of the market */
  variableFeeControl: number;
  /** Maximum number of bin crossed can be accumulated. Used to cap volatile fee rate. */
  maxVolatilityAccumulator: number;
};

export type UpdateDynamicFeeParametersInstructionDataArgs = {
  /** Filter period determine high frequency trading time window. */
  filterPeriod: number;
  /** Decay period determine when the volatile fee start decay / decrease. */
  decayPeriod: number;
  /** Reduction factor controls the volatile fee rate decrement rate. */
  reductionFactor: number;
  /** Used to scale the variable fee component depending on the dynamic of the market */
  variableFeeControl: number;
  /** Maximum number of bin crossed can be accumulated. Used to cap volatile fee rate. */
  maxVolatilityAccumulator: number;
};

export function getUpdateDynamicFeeParametersInstructionDataEncoder(): FixedSizeEncoder<UpdateDynamicFeeParametersInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['filterPeriod', getU16Encoder()],
      ['decayPeriod', getU16Encoder()],
      ['reductionFactor', getU16Encoder()],
      ['variableFeeControl', getU32Encoder()],
      ['maxVolatilityAccumulator', getU32Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_DYNAMIC_FEE_PARAMETERS_DISCRIMINATOR,
    })
  );
}

export function getUpdateDynamicFeeParametersInstructionDataDecoder(): FixedSizeDecoder<UpdateDynamicFeeParametersInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['filterPeriod', getU16Decoder()],
    ['decayPeriod', getU16Decoder()],
    ['reductionFactor', getU16Decoder()],
    ['variableFeeControl', getU32Decoder()],
    ['maxVolatilityAccumulator', getU32Decoder()],
  ]);
}

export function getUpdateDynamicFeeParametersInstructionDataCodec(): FixedSizeCodec<
  UpdateDynamicFeeParametersInstructionDataArgs,
  UpdateDynamicFeeParametersInstructionData
> {
  return combineCodec(
    getUpdateDynamicFeeParametersInstructionDataEncoder(),
    getUpdateDynamicFeeParametersInstructionDataDecoder()
  );
}

export type UpdateDynamicFeeParametersInput<
  TAccountLbPair extends string = string,
  TAccountAdmin extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  lbPair: Address<TAccountLbPair>;
  admin: TransactionSigner<TAccountAdmin>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  filterPeriod: UpdateDynamicFeeParametersInstructionDataArgs['filterPeriod'];
  decayPeriod: UpdateDynamicFeeParametersInstructionDataArgs['decayPeriod'];
  reductionFactor: UpdateDynamicFeeParametersInstructionDataArgs['reductionFactor'];
  variableFeeControl: UpdateDynamicFeeParametersInstructionDataArgs['variableFeeControl'];
  maxVolatilityAccumulator: UpdateDynamicFeeParametersInstructionDataArgs['maxVolatilityAccumulator'];
};

export function getUpdateDynamicFeeParametersInstruction<
  TAccountLbPair extends string,
  TAccountAdmin extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: UpdateDynamicFeeParametersInput<
    TAccountLbPair,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateDynamicFeeParametersInstruction<
  TProgramAddress,
  TAccountLbPair,
  TAccountAdmin,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    lbPair: { value: input.lbPair ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.lbPair),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    data: getUpdateDynamicFeeParametersInstructionDataEncoder().encode(
      args as UpdateDynamicFeeParametersInstructionDataArgs
    ),
    programAddress,
  } as UpdateDynamicFeeParametersInstruction<
    TProgramAddress,
    TAccountLbPair,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedUpdateDynamicFeeParametersInstruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    lbPair: TAccountMetas[0];
    admin: TAccountMetas[1];
    eventAuthority: TAccountMetas[2];
    program: TAccountMetas[3];
  };
  data: UpdateDynamicFeeParametersInstructionData;
};

export function parseUpdateDynamicFeeParametersInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateDynamicFeeParametersInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      lbPair: getNextAccount(),
      admin: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getUpdateDynamicFeeParametersInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
