/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { LB_CLMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_FEES_AND_REWARD2_DISCRIMINATOR = new Uint8Array([
  32, 142, 184, 154, 103, 65, 184, 88,
]);

export function getUpdateFeesAndReward2DiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_FEES_AND_REWARD2_DISCRIMINATOR
  );
}

export type UpdateFeesAndReward2Instruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountLbPair extends string | AccountMeta<string> = string,
  TAccountOwner extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountLbPair extends string
        ? WritableAccount<TAccountLbPair>
        : TAccountLbPair,
      TAccountOwner extends string
        ? ReadonlySignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateFeesAndReward2InstructionData = {
  discriminator: ReadonlyUint8Array;
  minBinId: number;
  maxBinId: number;
};

export type UpdateFeesAndReward2InstructionDataArgs = {
  minBinId: number;
  maxBinId: number;
};

export function getUpdateFeesAndReward2InstructionDataEncoder(): FixedSizeEncoder<UpdateFeesAndReward2InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['minBinId', getI32Encoder()],
      ['maxBinId', getI32Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_FEES_AND_REWARD2_DISCRIMINATOR,
    })
  );
}

export function getUpdateFeesAndReward2InstructionDataDecoder(): FixedSizeDecoder<UpdateFeesAndReward2InstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['minBinId', getI32Decoder()],
    ['maxBinId', getI32Decoder()],
  ]);
}

export function getUpdateFeesAndReward2InstructionDataCodec(): FixedSizeCodec<
  UpdateFeesAndReward2InstructionDataArgs,
  UpdateFeesAndReward2InstructionData
> {
  return combineCodec(
    getUpdateFeesAndReward2InstructionDataEncoder(),
    getUpdateFeesAndReward2InstructionDataDecoder()
  );
}

export type UpdateFeesAndReward2Input<
  TAccountPosition extends string = string,
  TAccountLbPair extends string = string,
  TAccountOwner extends string = string,
> = {
  position: Address<TAccountPosition>;
  lbPair: Address<TAccountLbPair>;
  owner: TransactionSigner<TAccountOwner>;
  minBinId: UpdateFeesAndReward2InstructionDataArgs['minBinId'];
  maxBinId: UpdateFeesAndReward2InstructionDataArgs['maxBinId'];
};

export function getUpdateFeesAndReward2Instruction<
  TAccountPosition extends string,
  TAccountLbPair extends string,
  TAccountOwner extends string,
  TProgramAddress extends Address = typeof LB_CLMM_PROGRAM_ADDRESS,
>(
  input: UpdateFeesAndReward2Input<
    TAccountPosition,
    TAccountLbPair,
    TAccountOwner
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateFeesAndReward2Instruction<
  TProgramAddress,
  TAccountPosition,
  TAccountLbPair,
  TAccountOwner
> {
  // Program address.
  const programAddress = config?.programAddress ?? LB_CLMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    position: { value: input.position ?? null, isWritable: true },
    lbPair: { value: input.lbPair ?? null, isWritable: true },
    owner: { value: input.owner ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.lbPair),
      getAccountMeta(accounts.owner),
    ],
    data: getUpdateFeesAndReward2InstructionDataEncoder().encode(
      args as UpdateFeesAndReward2InstructionDataArgs
    ),
    programAddress,
  } as UpdateFeesAndReward2Instruction<
    TProgramAddress,
    TAccountPosition,
    TAccountLbPair,
    TAccountOwner
  >);
}

export type ParsedUpdateFeesAndReward2Instruction<
  TProgram extends string = typeof LB_CLMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    position: TAccountMetas[0];
    lbPair: TAccountMetas[1];
    owner: TAccountMetas[2];
  };
  data: UpdateFeesAndReward2InstructionData;
};

export function parseUpdateFeesAndReward2Instruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateFeesAndReward2Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      position: getNextAccount(),
      lbPair: getNextAccount(),
      owner: getNextAccount(),
    },
    data: getUpdateFeesAndReward2InstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
