/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * The direction to round.  Used for pool token to trading token conversions to
 * avoid losing value on any deposit or withdrawal.
 */
export enum RoundDirection {
  Floor,
  Ceiling,
}

export type RoundDirectionArgs = RoundDirection;

export function getRoundDirectionEncoder(): FixedSizeEncoder<RoundDirectionArgs> {
  return getEnumEncoder(RoundDirection);
}

export function getRoundDirectionDecoder(): FixedSizeDecoder<RoundDirection> {
  return getEnumDecoder(RoundDirection);
}

export function getRoundDirectionCodec(): FixedSizeCodec<
  RoundDirectionArgs,
  RoundDirection
> {
  return combineCodec(getRoundDirectionEncoder(), getRoundDirectionDecoder());
}
