/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/**
 * The direction of a trade, since curves can be specialized to treat each
 * token differently (by adding offsets or weights)
 */
export enum TradeDirection {
  ZeroForOne,
  OneForZero,
}

export type TradeDirectionArgs = TradeDirection;

export function getTradeDirectionEncoder(): FixedSizeEncoder<TradeDirectionArgs> {
  return getEnumEncoder(TradeDirection);
}

export function getTradeDirectionDecoder(): FixedSizeDecoder<TradeDirection> {
  return getEnumDecoder(TradeDirection);
}

export function getTradeDirectionCodec(): FixedSizeCodec<
  TradeDirectionArgs,
  TradeDirection
> {
  return combineCodec(getTradeDirectionEncoder(), getTradeDirectionDecoder());
}
